name: 🐞 Bug
description: File a bug/issue
title: "【SRIM不具合】"
labels: ["001_利用者影響あり", "group:不具合対応"]
projects: ["yusukemihara/1"]
body:
- type: textarea
  attributes:
    label: 不具合内容
  validations:
    required: true
- type: textarea
  attributes:
    label: 発生日時
  validations:
    required: false
- type: textarea
  attributes:
    label: 発生医療機関（本番での発生の場合）
  validations:
    required: false
- type: textarea
  attributes:
    label: 対象機能・画面
  validations:
    required: false
- type: textarea
  attributes:
    label: 発生している事象
    description: キャプチャがあればキャプチャを添付
  validations:
    required: false
- type: textarea
  attributes:
    label: 影響範囲
    description: わかるようであれば記載する
  validations:
    required: false
- type: textarea
  attributes:
    label: 回避方法
    description: もしあれば記載する
  validations:
    required: false
